pull_request_rules:
  - name: "Rebase on passing tests"
    conditions:
      - and:
        - author=renovate[bot]
        - or:
          - check-success=success
          - check-skipped=success
          - check-neutral=success
        - -draft
        - -conflict
    actions:
      merge:
        method: rebase
  
  