pull_request_rules:
  - name: "Rebase on passing tests"
    conditions:
      - author=renovate[bot]
      - check-success=success
      - -draft
      - -conflict
    actions:
      merge:
        method: rebase
  
  