pull_request_rules:
  - name: "Rebase on passing tests"
    conditions:
      - author=renovate[bot]
      - check-success=test-deploy
      - check-success=release
      - check-success=test: Linux
      - check-success=test: Windows
      - check-success=test: MacOs
    actions:
      rebase:
  
  