[versions]
alchemist = "<the version of alchemist is here>"

[libraries]
alchemist = { module = "it.unibo.alchemist:alchemist", version.ref = "alchemist" }
alchemist-full = { module = "it.unibo.alchemist:alchemist-full", version.ref = "alchemist" }

[bundles]
alchemist = [
    "alchemist",
    "alchemist-full",
]