@startuml
interface Vehicle<T> {
}
abstract class AbstractVehicle<T> {
}
class Bicycle<T, P> {
}
class Car<T : FourWheels<T, O, A>, O : Wheeled<T, O>, A : ComplexGeneric<T, O, A>> {
    +bike: Bicycle
}
interface FourWheels<T, P, A> {
}
interface TwoWheels<T, P> {
}
interface Wheeled<T, P> {
}
Vehicle <|.. AbstractVehicle
AbstractVehicle <|.. Bicycle
TwoWheels <|.. Bicycle
AbstractVehicle <|.. Car
FourWheels <|.. Car
Wheeled <|.. FourWheels
Wheeled <|.. TwoWheels
Vehicle <|.. Wheeled
@enduml