@startuml
interface Vehicle<T> {
    +{abstract} start(): Unit
    +{abstract} stop(): Unit
}

abstract class AbstractVehicle<T> {
    +{abstract} description(): String
    +start(): Unit
    +stop(): Unit
}

class Bicycle<T,\nP> {
    +description(): String
}

class Car<T : FourWheels<T, O, A>,\nO : Wheeled<T, O>,\nA : ComplexGeneric<T, O, A>> {
    +bike: Bicycle<T, O>
    +description(): String
}

interface FourWheels<T,\nP,\nA> {
}

interface TwoWheels<T,\nP> {
}

interface Wheeled<T,\nP> {
}

@enduml
