name: CI
on:
  push:
    paths-ignore:
      - 'CHANGELOG.md'
      - '.gitignore'
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  # Runs all tests
  build:
    name: Test
    strategy:
      matrix:
        os: [windows, macos, ubuntu]
    runs-on: ${{ matrix.os }}-latest
    timeout-minutes: 120
    concurrency:
      group: ${{ github.workflow }}-build-${{ matrix.os }}-${{ github.event.number || github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: danysk/action-checkout@0.2.21
      - uses: DanySK/build-check-deploy-gradle-action@3.5.11
        with:
          build_command: 'true'
          should-run-codecov: ${{ contains('Linux', runner.os) }}
  test-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    concurrency:
      group: ${{ github.workflow }}-test-deploy-${{ github.event.number || github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: danysk/action-checkout@0.2.21
      - uses: DanySK/build-check-deploy-gradle-action@3.5.11
        with:
          build-command: true
          check-command: |
            ./gradlew tasks | grep releaseStagingRepositoryOnMavenCentral
            ./gradlew tasks | grep closeStagingRepositoryOnMavenCentral
          should-run-codecov: false
          should-deploy: false
          should-validate-wrapper: false
      - uses: DanySK/build-check-deploy-gradle-action@3.5.11
        if: contains(github.repository, 'Kotlin2PlantUML') && contains('push workflow_dispatch', github.event_name)
        with:
          build-command: true
          check-command: true
          deploy-command: ./gradlew uploadKotlin close || ./gradlew uploadKotlin close || ./gradlew uploadKotlin close
          java-version: 11
          should-run-codecov: false
          should-deploy: true
          should-validate-wrapper: false
          maven-central-username: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          maven-central-password: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          signing-key: ${{ secrets.SIGNING_KEY }}
          signing-password: ${{ secrets.SIGNING_PASSWORD }}
  release:
    concurrency:
      # Only one release job at a time. Strictly sequential.
      group: release
    needs:
      - build
      - test-deploy
    runs-on: ubuntu-latest
    if: >-
      contains('push workflow_dispatch', github.event_name)
      && contains(github.repository, 'Kelvindev15/Kotlin2PlantUML')
    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          submodules: recursive
      - uses: actions/setup-node@v4.0.4
        with:
          node-version: '20.15'    
      - uses: DanySK/build-check-deploy-gradle-action@3.5.11
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          java-version: 11
          build-command: true
          check-command: true
          deploy-command: |
            npm install
            npx semantic-release
          should-run-codecov: false
          should-deploy: true
          should-validate-wrapper: false
          github-token: ${{ secrets.GH_TOKEN }}
          maven-central-username: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          maven-central-password: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          signing-key: ${{ secrets.SIGNING_KEY }}
          signing-password: ${{ secrets.SIGNING_PASSWORD }}
  success:
    runs-on: ubuntu-24.04
    needs:
      - build
      - release
      - test-deploy
    if: >-
      always() && (
        contains(join(needs.*.result, ','), 'failure')
        || !contains(join(needs.*.result, ','), 'cancelled')
      )
    steps:
      - name: Verify that there were no failures
        run: ${{ !contains(join(needs.*.result, ','), 'failure') }}
